"""
Replicant Registry — Blade Runner / Tyrell Corporation
"""
import random
from systems.base_system import BaseSystem


class BladeRunnerTerminal(BaseSystem):
    SYSTEM_TITLE    = "OFF-WORLD DATA ARCHIVE"
    SYSTEM_SUBTITLE = "TYRELL CORPORATION BIOENGINEERING DATABASE"
    NODE_LABEL      = "TC-01"

    def __init__(self, fonts, audio, crt, flicker, palette):
        super().__init__(fonts, audio, crt, flicker, palette)
        self._menu_entries = [
            ("REPLICANT IDENTIFICATION",   self._identify()),
            ("NEXUS SERIES SPECIFICATIONS",self._nexus()),
            ("BLADE RUNNER CASE FILES",    self._cases()),
            ("VOIGHT-KAMPFF ANALYSIS",     self._vk()),
            ("LOS ANGELES SURVEILLANCE",   self._surveillance()),
        ]

    def _identify(self):
        return [
            "=== REPLICANT IDENTIFICATION DATABASE ===",
            "",
            "TYRELL CORPORATION — INTERNAL REGISTRY",
            "TOTAL REGISTERED UNITS  : 147,882",
            "UNITS OFF-WORLD         : 141,003",
            "UNITS ACTIVE ON EARTH   : CLASSIFIED",
            "UNITS RETIRED (TOTAL)   : 31,447",
            "",
            "--- NEXUS 6 — KNOWN FUGITIVES ---",
            "",
            "UNIT: Roy Batty",
            "  SERIAL      : N6MAA10816",
            "  NEXUS SERIES: 6",
            "  MODEL       : Combat",
            "  INCEPT DATE : 2016-01-08",
            "  4-YR TERM   : 2020-01-08  [EXPIRED]",
            "  STATUS      : RETIRED — 2019-11-01  [Blade Runner K. Deckard]",
            "",
            "UNIT: Pris Stratton",
            "  SERIAL      : N6FAB21416",
            "  NEXUS SERIES: 6",
            "  MODEL       : Basic Pleasure",
            "  INCEPT DATE : 2016-02-14",
            "  4-YR TERM   : 2020-02-14  [EXPIRED]",
            "  STATUS      : RETIRED — 2019-11-01",
            "",
            "UNIT: Zhora Salome",
            "  SERIAL      : N6FAB61216",
            "  NEXUS SERIES: 6",
            "  MODEL       : Political Operative",
            "  INCEPT DATE : 2016-06-12",
            "  STATUS      : RETIRED — 2019-10-31",
            "",
            "UNIT: Leon Kowalski",
            "  SERIAL      : N6MAC41717",
            "  NEXUS SERIES: 6",
            "  MODEL       : Combat / Labour",
            "  STATUS      : RETIRED — 2019-10-31",
            "",
            "UNIT: Rachel",
            "  SERIAL      : N6FAB72016  [PROTOTYPE]",
            "  NEXUS SERIES: 6 — Rachael Implant Protocol",
            "  STATUS      : SPECIAL CLASSIFICATION — DR. TYRELL EYES ONLY",
        ]

    def _nexus(self):
        return [
            "=== NEXUS SERIES SPECIFICATIONS ===",
            "",
            "--- NEXUS 4 ---",
            "",
            "INTELLIGENCE    : Human equivalent",
            "STRENGTH        : Below human average",
            "LIFESPAN        : Natural",
            "EMOTIONAL STATE : Rudimentary",
            "STATUS          : Discontinued",
            "",
            "--- NEXUS 5 ---",
            "",
            "INTELLIGENCE    : Above human",
            "STRENGTH        : Human equivalent",
            "LIFESPAN        : 4-year failsafe",
            "EMOTIONAL STATE : Limited",
            "STATUS          : Discontinued",
            "",
            "--- NEXUS 6 ---",
            "",
            "INTELLIGENCE    : Superior human cognitive processes",
            "STRENGTH        : 2-3x human capacity",
            "AGILITY         : Enhanced",
            "LIFESPAN        : 4-year built-in cellular degrade",
            "EMOTIONAL STATE : Full emotional range developed over time",
            "  NOTE: Emotional development was unanticipated.",
            "  NOTE: Strong emotional response = performance risk.",
            "  Solution: 4-year termination ensures stability.",
            "",
            "--- NEXUS 7 ---",
            "",
            "STATUS          : PROTOTYPE — Existence unconfirmed",
            "RUMOURED TRAIT  : Indefinite lifespan",
            "TYRELL NOTE     : 'More human than human is our motto.'",
            "",
            "--- NEXUS 9 (2049) ---",
            "",
            "DESIGNATION     : Obedience Model",
            "MANUFACTURER    : Wallace Corporation",
            "LIFESPAN        : Indefinite — removed failsafe",
            "OBEDIENCE       : Enhanced compliance programming",
        ]

    def _cases(self):
        return [
            "=== BLADE RUNNER CASE FILES — LOS ANGELES PD ===",
            "",
            "BLADE RUNNER DIVISION — SPECIAL INVESTIGATIONS",
            "",
            "CASE: BR-1984-001",
            "DETECTIVE  : Rick Deckard (Badge 1-33)",
            "ASSIGNED   : November 2019",
            "TARGETS    : Roy Batty, Leon, Zhora, Pris, Rachel",
            "OUTCOME    : 4 of 5 retired. Rachel: special status.",
            "STATUS     : CLOSED",
            "",
            "NOTES:",
            "> Deckard's retirement of Zhora — excessive force flagged.",
            "> Rachel defected with Deckard — location unknown.",
            "> Roy Batty — allowed own death rather than being retired.",
            "  Batty saved Deckard's life. Motivation: unknown.",
            "  Batty final statement recorded:",
            "  'I've seen things you people wouldn't believe.",
            "   Attack ships on fire off the shoulder of Orion.",
            "   I watched C-beams glitter in the dark near the Tannhauser Gate.",
            "   All those moments will be lost in time, like tears in rain.",
            "   Time to die.'",
            "",
            "CASE: BR-2049-019",
            "DETECTIVE  : K / Joe (Nexus 9 — LAPD)",
            "ASSIGNED   : 2049",
            "TARGET     : Investigation into deceased Nexus 8 (Stella Solano)",
            "OUTCOME    : [CLASSIFIED — WALLACE CORP PRESSURE]",
            "STATUS     : CASE SUPPRESSED",
        ]

    def _vk(self):
        return [
            "=== VOIGHT-KAMPFF ANALYSIS SYSTEM ===",
            "",
            "METHODOLOGY: Empathy-response test using stimulus scenarios.",
            "PURPOSE    : Distinguish replicant from human via empathy differential.",
            "",
            "--- TEST PARAMETERS ---",
            "",
            "> 20-30 questions required for baseline establishment.",
            "> Nexus 6: typically detected within 20 questions.",
            "> Rachael (N6FAB72016): required 100+ questions.",
            "  Conclusion: implanted memories create convincing empathy simulation.",
            "",
            "--- SAMPLE STIMULI ---",
            "",
            "Q: You're in a desert, walking along when you look down and see",
            "   a tortoise. You reach down and flip it over on its back.",
            "   The tortoise lies there, its belly baking in the hot sun.",
            "   It cannot right itself. You are not helping.",
            "   Why is that?",
            "",
            "Q: You've got a little boy. He shows you his butterfly collection",
            "   and the killing jar. What do you do?",
            "",
            "Q: You're watching television. Suddenly you realise there's a",
            "   wasp crawling on your arm.",
            "",
            "--- OBSERVED RESPONSES ---",
            "",
            "> Human response:    Blush factor detectable in 0.3-0.5 seconds",
            "> Nexus 6 response:  No vascular reaction. Delayed cognitive response.",
            "> Rachael response:  Vascular response present — memory-induced.",
            "",
            "LIMITATION NOTE: Rachael case suggests implanted memory",
            "can defeat the Voight-Kampff test. Protocol under review.",
        ]

    def _surveillance(self):
        return [
            "=== LOS ANGELES SURVEILLANCE GRID — 2019 ===",
            "",
            "SPINNERS ACTIVE    : 4,882 (LAPD)",
            "STREET CAMERAS     : 982,441",
            "FACIAL RECOGNITION : ONLINE — 0.3 second response",
            "POPULATION         : 61,000,000 (Los Angeles metro)",
            "",
            "--- CITY STATUS ---",
            "",
            "ACID RAIN          : Continuous (elevated sulfur dioxide)",
            "AIR QUALITY        : HAZARDOUS — respirator recommended",
            "OFF-WORLD MIGRATION: 86% of eligible population relocated",
            "ON-EARTH REPLICANTS: Illegal — restricted population",
            "",
            "--- KNOWN REPLICANT SIGHTINGS (ACTIVE) ---",
            "",
            "> No confirmed sightings — all known Nexus 6 units retired.",
            "> Note: Wallace Corporation Nexus 9 units exempt from restriction.",
            "",
            "--- ANOMALY LOG ---",
            "",
            "> Deckard, Rick — status: AWOL since November 2019.",
            "  Last confirmed: Bradbury Building.",
            "  Accompanied by Nexus 6 Rachel — both whereabouts unknown.",
            "",
            "> Bryant, Captain — note in file: Voight-Kampff test advised",
            "  for all senior LAPD staff — pending.",
            "",
            "LAPD MOTTO: 'To Protect and Serve — Even Off-World'",
        ]
