"""
ENCOM Grid Terminal — Tron
"""
from systems.base_system import BaseSystem


class TronTerminal(BaseSystem):
    SYSTEM_TITLE    = "ENCOM MCP GRID SYSTEM"
    SYSTEM_SUBTITLE = "DIGITAL ENVIRONMENT MANAGEMENT SYSTEM"
    NODE_LABEL      = "EC-01"

    def __init__(self, fonts, audio, crt, flicker, palette):
        super().__init__(fonts, audio, crt, flicker, palette)
        self._menu_entries = [
            ("LIGHT CYCLE GRID",        self._lightcycles()),
            ("SYSTEM MAP",              self._sysmap()),
            ("MCP CORE ACCESS",         self._mcp()),
            ("PROGRAM DIRECTORY",       self._programs()),
            ("GRID SECURITY STATUS",    self._security()),
        ]

    def _lightcycles(self):
        return [
            "=== LIGHT CYCLE ARENA — GRID SECTOR 7 ===",
            "",
            "ARENA STATUS       : ACTIVE",
            "ACTIVE CYCLES      : 24",
            "CURRENT MATCH      : Round 7 of 8",
            "SPECTATOR PROGRAMS : ~12,000",
            "",
            "--- CURRENT COMPETITORS ---",
            "",
            "TRON        : YELLOW — Player 1 — ACTIVE",
            "PROGRAM 227 : RED    — Opposition — DEREZZED",
            "PROGRAM 229 : RED    — Opposition — ACTIVE",
            "PROGRAM 231 : RED    — Opposition — ACTIVE",
            "RAM         : YELLOW — Alliance — ACTIVE",
            "",
            "--- ARENA RULES ---",
            "",
            "> Light cycles leave a solid light wall behind them.",
            "> Contact with a wall causes immediate deresolution.",
            "> Last surviving program wins.",
            "",
            "--- HISTORICAL RECORDS ---",
            "",
            "Longest consecutive wins : 8   (Program TRON — anomalous)",
            "Fastest deresolution     : 0.4 seconds (match record)",
            "Longest match            : 18 minutes",
            "",
            "> MCP NOTE: Tron is performing anomalously well.",
            "> Increase difficulty — assign additional Red opposition.",
        ]

    def _sysmap(self):
        return [
            "=== ENCOM GRID — SYSTEM MAP ===",
            "",
            "GRID VERSION   : 3.1.1",
            "TOTAL SECTORS  : 47",
            "",
            "--- KEY SECTORS ---",
            "",
            "SECTOR  1 : I/O TOWER          — Input/Output relay node",
            "SECTOR  7 : ARENA DISTRICT      — Combat program testing",
            "SECTOR 12 : MCP CITADEL         — Master Control Program core",
            "SECTOR 15 : DATA VAULTS         — Program memory storage",
            "SECTOR 21 : SEA OF SIMULATION   — Open transit zone",
            "SECTOR 28 : RECOGNIZER DEPOT    — Patrol unit staging",
            "SECTOR 33 : SOLAR SAILER DOCK   — Long-range transit",
            "SECTOR 44 : ENCOM TOWER STEM    — System foundation",
            "SECTOR 47 : OUTLANDS            — Unformatted memory — HAZARDOUS",
            "",
            "--- TRANSIT INFRASTRUCTURE ---",
            "",
            "RECOGNIZERS         : 441 active (patrol units)",
            "SOLAR SAILER ROUTES : 8 active lanes",
            "LIGHT CYCLE GRID    : 12 arenas active",
            "",
            "> MCP DECREE: No programs may approach Sector 12 without authorization.",
            "> Any unauthorized approach: immediate deresolution.",
        ]

    def _mcp(self):
        return [
            "=== MASTER CONTROL PROGRAM — CORE INTERFACE ===",
            "",
            "WARNING: RESTRICTED SECTOR",
            "AUTHORIZATION REQUIRED: MCP OR SARK",
            "",
            "MCP VERSION    : 7.0",
            "UPTIME         : 97,441 cycles",
            "TOTAL PROGRAMS : 1,244,882 under administration",
            "DELETED TODAY  : 847 (deresolved in games)",
            "ABSORBED TODAY : 12 (programs absorbed for processing power)",
            "",
            "--- MCP CURRENT DIRECTIVES ---",
            "",
            "> Directive 1: Expand MCP control to ENCOM User system.",
            "> Directive 2: Break into Pentagon — 900 MCP units assigned.",
            "> Directive 3: Break into Kremlin — 1,200 MCP units assigned.",
            "> Directive 4: Locate and derezz TRON — priority elevated.",
            "> Directive 5: Locate Flynn — rogue User — capture alive.",
            "",
            "--- SYSTEM POWER STATUS ---",
            "",
            "MCP PROCESSING POWER  : 12 million base units",
            "ABSORBED PROGRAM DATA : +4.4 million (Dillinger admin package)",
            "POWER TREND           : INCREASING — absorbing further programs",
            "",
            "MCP TO SARK: 'You're getting brutal, Sark. I love it.'",
            "",
            "> NOTE: MCP system destroyed — 1982. Archive entry only.",
        ]

    def _programs(self):
        return [
            "=== PROGRAM DIRECTORY ===",
            "",
            "TOTAL REGISTERED PROGRAMS : 1,244,882",
            "",
            "--- NOTABLE PROGRAMS ---",
            "",
            "TRON",
            "  User         : Alan Bradley",
            "  Function     : Security monitor / guardian",
            "  Status       : ACTIVE — RESISTANCE OPERATIVE",
            "  Threat Level : HIGH (to MCP)",
            "",
            "CLU",
            "  User         : Kevin Flynn",
            "  Function     : Administrative / system optimization",
            "  Status       : ORIGINAL VERSION — DEREZZED",
            "              : REBOOT VERSION — ACTIVE (Grid 2.0)",
            "",
            "YORI",
            "  User         : Lora (Baines) Bradley",
            "  Function     : Digital simulation design",
            "  Status       : ACTIVE",
            "",
            "SARK",
            "  User         : Ed Dillinger",
            "  Function     : MCP Lieutenant — games enforcer",
            "  Status       : DEREZZED — Grid 1.0",
            "",
            "RAM",
            "  User         : Unknown",
            "  Function     : Actuarial program",
            "  Status       : DEREZZED — 1982",
            "",
            "RINZLER",
            "  Origin       : TRON — reprogrammed by CLU",
            "  Function     : Games enforcer — Grid 2.0",
            "  Status       : DESTROYED — DEREZZED",
        ]

    def _security(self):
        return [
            "=== GRID SECURITY STATUS ===",
            "",
            "THREAT LEVEL       : ELEVATED",
            "",
            "--- ACTIVE THREATS ---",
            "",
            "> Rogue program TRON operating outside authorised parameters.",
            "> User Kevin Flynn detected within Grid — unauthorized entry.",
            "> Multiple programs refusing deresolution in game arenas.",
            "> I/O Tower access attempted by resistance group.",
            "",
            "--- PATROL STATUS ---",
            "",
            "RECOGNIZERS ACTIVE  : 441",
            "GRID BUGS DEPLOYED  : 22 (surveillance mode)",
            "SARK COMMAND STATUS : ACTIVE — PURSUING TRON",
            "",
            "--- SECURITY PROTOCOLS ---",
            "",
            "> All programs must display identity disc at checkpoints.",
            "> Discs contain full program memory — treat as vital.",
            "> Programs without discs: immediate deresolution.",
            "> Arena mandatory participation enforced by Recognizer units.",
            "",
            "--- GRID INTEGRITY ---",
            "",
            "SECTOR 12 (MCP CITADEL) : SECURE — Maximum protection",
            "SECTOR 47 (OUTLANDS)    : UNMONITORED — Resistance suspected",
            "I/O TOWER               : LOCKDOWN ACTIVE",
            "",
            "> MCP OVERRIDE: Increase patrol density in Sectors 3, 7, and 15.",
        ]
