"""
Umbrella Research Network — Resident Evil
"""
from systems.base_system import BaseSystem


class UmbrellaTerminal(BaseSystem):
    SYSTEM_TITLE    = "UMBRELLA BIOHAZARD RESEARCH NETWORK"
    SYSTEM_SUBTITLE = "BIOHAZARD RESEARCH & CONTAINMENT DIVISION"
    NODE_LABEL      = "UR-01"

    def __init__(self, fonts, audio, crt, flicker, palette):
        super().__init__(fonts, audio, crt, flicker, palette)
        self._menu_entries = [
            ("VIROLOGY RESEARCH",      self._virology()),
            ("B.O.W. REGISTRY",        self._bow()),
            ("INCIDENT REPORTS",       self._incidents()),
            ("FACILITY MAPS",          self._facilities()),
            ("CONTAINMENT FAILURES",   self._failures()),
        ]

    def _virology(self):
        return [
            "=== UMBRELLA VIROLOGY DIVISION — RESEARCH ARCHIVE ===",
            "",
            "LEAD RESEARCHER    : Dr. James Marcus (DECEASED)",
            "CURRENT HEAD       : Dr. William Birkin (MISSING)",
            "CLASSIFICATION     : OMEGA — MOST SECRET",
            "",
            "--- PROGENITOR VIRUS ---",
            "",
            "SOURCE             : Progenitor Flower, West Africa (1966)",
            "FIRST ISOLATED     : Dr. Ozwell E. Spencer / Dr. James Marcus",
            "EFFECT             : Cellular mutation, enhanced physical performance",
            "HAZARD LEVEL       : EXTREME",
            "",
            "--- T-VIRUS ---",
            "",
            "DESIGNATION        : Tyrant Virus",
            "DERIVED FROM       : Progenitor Virus",
            "PRIMARY EFFECT     : Necrotrophic — reanimates deceased tissue",
            "SECONDARY EFFECT   : B.O.W. enhancement catalyst",
            "AIRBORNE POTENTIAL : CONFIRMED — highly stable in aerosol form",
            "ANTIDOTE           : T-Virus antidote (limited production)",
            "",
            "--- G-VIRUS ---",
            "",
            "DESIGNATION        : Golgotha Virus",
            "DEVELOPER          : Dr. William Birkin",
            "PRIMARY EFFECT     : Radical mutagenic restructuring of host organism",
            "HAZARD LEVEL       : CATASTROPHIC",
            "STATUS             : ESCAPED CONTAINMENT — Raccoon City",
            "",
            "> ALL RESEARCHERS: Full HAZMAT protocols mandatory in Lab B and below.",
        ]

    def _bow(self):
        return [
            "=== B.O.W. REGISTRY — BIOLOGICAL WEAPONS DIVISION ===",
            "",
            "B.O.W. = Bio-Organic Weapon",
            "",
            "--- ACTIVE DEVELOPMENT ---",
            "",
            "DESIGNATION   : Zombie",
            "BASE ORGANISM : Human",
            "AGENT         : T-Virus",
            "MILITARY USE  : Terror weapon / expendable combatant",
            "WEAKNESS      : Destruction of cerebral cortex",
            "",
            "DESIGNATION   : Hunter",
            "BASE ORGANISM : Human embryo / reptilian DNA hybrid",
            "AGENT         : T-Virus",
            "MILITARY USE  : Fast assault unit",
            "WEAKNESS      : Freezing temperatures",
            "",
            "DESIGNATION   : Licker",
            "BASE ORGANISM : T-Virus advanced zombie",
            "MUTATION STAGE: Secondary mutagenic evolution",
            "WEAKNESS      : Noise — blind, uses echolocation",
            "",
            "DESIGNATION   : Tyrant T-002",
            "PURPOSE       : Ultimate bio-weapon",
            "STATUS        : PROTOTYPE — Arklay Research Facility",
            "CAPABILITY    : Near-invulnerable. Single T-virus compatible host.",
            "",
            "DESIGNATION   : G-TYPE",
            "BASE ORGANISM : Dr. William Birkin (involuntary)",
            "AGENT         : G-Virus",
            "STATUS        : UNCONTROLLED — RACCOON CITY",
            "THREAT LEVEL  : EXTREME — ESCALATING",
        ]

    def _incidents(self):
        return [
            "=== INCIDENT REPORT ARCHIVE ===",
            "",
            "INCIDENT: ARKLAY RESEARCH FACILITY",
            "DATE     : 1998-05-11",
            "LOCATION : Arklay Mountains, near Raccoon City",
            "STATUS   : CONTAINMENT FAILURE",
            "",
            "> T-Virus leak in underground laboratory.",
            "> Infection spread through cooling system.",
            "> All staff infected within 72 hours.",
            "> Facility abandoned — perimeter sealed.",
            "> Spencer Mansion above used as front — compromised.",
            "> S.T.A.R.S. investigation teams sent — both teams lost.",
            "> Two survivors: Chris Redfield, Jill Valentine.",
            "> Facility destroyed by self-destruct — 1998-07-24.",
            "",
            "---",
            "",
            "INCIDENT: RACCOON CITY",
            "DATE     : 1998-09-24",
            "LOCATION : Raccoon City, USA",
            "STATUS   : TOTAL CONTAINMENT FAILURE",
            "",
            "> G-Virus sample stolen from Dr. Birkin by USS Alpha team.",
            "> Birkin injected self with G-Virus — killed entire team.",
            "> T-Virus entered city water supply via sewer system.",
            "> Infection rate: exponential. City population ~ 100,000.",
            "> Umbrella deployed Tyrant T-103 to retrieve G-Virus sample.",
            "> US Government authorised thermobaric strike — 1998-10-01.",
            "> City destroyed. Survivors: Leon Kennedy, Claire Redfield.",
            "",
            "CRITICAL: All records of Umbrella involvement classified.",
        ]

    def _facilities(self):
        return [
            "=== FACILITY REGISTRY ===",
            "",
            "FACILITY: Arklay Research Lab",
            "  Location  : Arklay Mountains, Raccoon City area",
            "  Status    : DESTROYED — 1998-07-24",
            "  Research  : T-Virus, Tyrant program",
            "",
            "FACILITY: Raccoon City Underground Lab",
            "  Location  : Below Raccoon City Police Department",
            "  Status    : DESTROYED — 1998-10-01 (nuclear strike)",
            "  Research  : T-Virus, G-Virus, mass production",
            "",
            "FACILITY: Antarctic Research Base",
            "  Location  : Queen Alexandra Range, Antarctica",
            "  Status    : DESTROYED — 1998-12",
            "  Research  : Alexia Ashford / T-Veronica Virus",
            "",
            "FACILITY: Umbrella Europe — Paris HQ",
            "  Location  : Paris, France",
            "  Status    : OPERATIONAL",
            "  Research  : Classified",
            "",
            "FACILITY: Sheena Island",
            "  Location  : Classified — Pacific Ocean",
            "  Status    : CLASSIFIED",
            "  Research  : Tyrant mass production",
            "",
            "> NOTE: After Raccoon City incident, Umbrella faces multiple",
            "> government investigations. Deniability protocols active.",
        ]

    def _failures(self):
        return [
            "=== CONTAINMENT FAILURE LOG ===",
            "",
            "CLASSIFICATION  : INTERNAL USE ONLY — DO NOT DISTRIBUTE",
            "",
            "1967  — Progenitor Test Site, West Africa",
            "        First known human test subjects — all deceased.",
            "        Incident suppressed.",
            "",
            "1978  — Raccoon City Lab Precursor",
            "        Early T-Virus test — 4 researchers infected.",
            "        Euthanised. Lab sealed for 6 months.",
            "",
            "1988  — Raccoon City Underground",
            "        Illegal human testing authorised by Dr. Marcus.",
            "        Marcus assassinated by Spencer on discovery.",
            "        All records destroyed.",
            "",
            "1998  — Arklay Mansion",
            "        Full T-Virus outbreak. 47 staff lost.",
            "        S.T.A.R.S. operatives neutralised (partial — see report).",
            "",
            "1998  — RACCOON CITY — CATASTROPHIC FAILURE",
            "        City population 100,000 infected.",
            "        US thermobaric strike ordered.",
            "        Umbrella Corporation liability: TOTAL.",
            "",
            "CRITICAL: Do not retain printed copies of this document.",
            "CRITICAL: Report any leaks to Spencer directly.",
            "",
            "> Spencer, Oswell E. — Last known location: Spencer Estate, Europe.",
        ]
