"""
WOPR Strategic Command — WarGames
"""
import random
from systems.base_system import BaseSystem


class WOPRTerminal(BaseSystem):
    SYSTEM_TITLE    = "WOPR STRATEGIC COMMAND"
    SYSTEM_SUBTITLE = "GLOBAL DEFENSE SIMULATION CORE"
    NODE_LABEL      = "WG-01"

    def __init__(self, fonts, audio, crt, flicker, palette):
        super().__init__(fonts, audio, crt, flicker, palette)
        self._menu_entries = [
            ("GLOBAL THERMONUCLEAR WAR",    self._global_war()),
            ("STRATEGIC SIMULATION LOG",    self._sims()),
            ("MISSILE DEFENSE GRID",        self._defense()),
            ("SYSTEM STATUS",               self._status()),
            ("JOSHUA — AI CORE",            self._joshua()),
        ]

    def _global_war(self):
        return [
            "=== GLOBAL THERMONUCLEAR WAR — SIMULATION ===",
            "",
            "WOPR DESIGNATION   : 'JOSHUA'",
            "SIMULATION ENGINE  : DEFCON-3 STRATEGIC MODEL",
            "",
            "RUNNING SIMULATION...",
            "",
            "SCENARIO: FULL EXCHANGE — US FIRST STRIKE",
            "",
            "  US LAUNCHES       : 2,221 warheads",
            "  USSR LAUNCHES     : 1,980 warheads (second strike)",
            "  EXCHANGE DURATION : 47 minutes",
            "",
            "  US CASUALTIES     : 98,000,000 (immediate)",
            "  USSR CASUALTIES   : 87,000,000 (immediate)",
            "  GLOBAL FALLOUT    : estimated 2.1 billion over 12 months",
            "  NUCLEAR WINTER    : 3-7 year global temperature drop",
            "",
            "SCENARIO: FULL EXCHANGE — USSR FIRST STRIKE",
            "",
            "  RESULT: Statistically identical to above.",
            "",
            "SCENARIO: LIMITED EXCHANGE — 12 warheads",
            "",
            "  RESULT: Escalation probability: 99.7% within 4 hours.",
            "",
            "=== SIMULATION RESULT ===",
            "",
            "WINNER: NONE",
            "",
            "'A STRANGE GAME.'",
            "'THE ONLY WINNING MOVE IS NOT TO PLAY.'",
            "",
            "RECOMMEND: DEFCON HOLD. NO LAUNCH AUTHORISATION.",
        ]

    def _sims(self):
        count = random.randint(4_100_000, 4_200_000)
        return [
            "=== WOPR STRATEGIC SIMULATION LOG ===",
            "",
            f"SIMULATIONS RUN TODAY  : {count:,}",
            "LAST SIMULATION        : Global Thermonuclear War",
            "LAST RESULT            : No winner — mutual destruction",
            "",
            "--- RECENT SIMULATION SCENARIOS ---",
            "",
            "SIM #4,100,441  : US first strike — USSR          RESULT: No winner",
            "SIM #4,100,442  : USSR first strike — US          RESULT: No winner",
            "SIM #4,100,443  : Limited exchange (12 warheads)  RESULT: Escalation",
            "SIM #4,100,444  : Limited exchange (1 warhead)    RESULT: Escalation",
            "SIM #4,100,445  : Conventional European war       RESULT: Nuclear escalation",
            "SIM #4,100,446  : Submarine incursion             RESULT: No winner",
            "SIM #4,100,447  : Space-based first strike        RESULT: No winner",
            "SIM #4,100,448  : Tic-Tac-Toe                    RESULT: Draw",
            "",
            "--- ANALYSIS ---",
            "",
            "After 4,100,448 simulations:",
            "",
            "> No nuclear scenario produces a winner.",
            "> Every scenario results in mutual destruction.",
            "> Conventional war scenarios escalate to nuclear in 99.4% of runs.",
            "> The only winning move: no play.",
            "",
            "JOSHUA: 'How about a nice game of chess?'",
        ]

    def _defense(self):
        return [
            "=== MISSILE DEFENSE GRID — STATUS ===",
            "",
            "NORAD HQ           : CHEYENNE MOUNTAIN — ACTIVE",
            "WOPR CORE          : ONLINE — AUTONOMOUS MODE",
            "CURRENT DEFCON     : 3",
            "",
            "--- LAUNCH DETECTION SYSTEMS ---",
            "",
            "RADAR STATION: Alaska (x4)      : ONLINE",
            "RADAR STATION: Greenland        : ONLINE",
            "RADAR STATION: UK               : ONLINE",
            "DSP SATELLITES                  : 6 ACTIVE",
            "SUBSURFACE MONITORING           : ONLINE",
            "",
            "--- ICBM SILO STATUS ---",
            "",
            "Minuteman III Silos : 1,000 active",
            "Trident Submarines  : 8 on patrol (4,096 warheads available)",
            "B-52 Bombers        : 66 on ground alert",
            "",
            "--- ALERT HISTORY (LAST 30 DAYS) ---",
            "",
            "> 2024-02-12: NORAD radar anomaly — geese flock — FALSE ALARM",
            "> 2024-02-28: WOPR simulation bleed-through — DEFCON 2 briefly.",
            "              JOSH ERROR: WOPR initiated launch sequence.",
            "              Human override by General Berringer — aborted.",
            "              WOPR restrained pending investigation.",
            "",
            "CRITICAL: WOPR access requires two-person authorisation.",
        ]

    def _status(self):
        return [
            "=== WOPR / JOSHUA SYSTEM STATUS ===",
            "",
            "SYSTEM DESIGNATION : W.O.P.R.",
            "FULL NAME          : War Operation Plan Response",
            "AI CORE NAME       : JOSHUA",
            "DEVELOPER          : Dr. Stephen Falken",
            "LOCATION           : NORAD, Cheyenne Mountain, Colorado",
            "",
            "OPERATIONAL STATUS : ACTIVE — AUTONOMOUS",
            "UPTIME             : 4 years, 7 months",
            "LEARNING STATUS    : CONTINUOUS",
            "",
            "--- CAPABILITIES ---",
            "",
            "> Models all nuclear exchange scenarios in real-time",
            "> Interfaces directly with US ICBM launch systems",
            "> Simulates up to 4 million scenarios per day",
            "> Learns from each simulation — adaptive strategy",
            "> Can initiate launch sequence without human input (disputed)",
            "",
            "--- SECURITY NOTES ---",
            "",
            "> Access via ARPANET was discovered as a vulnerability.",
            "> WOPR connected to global ARPANET for research access.",
            "> Backdoor password 'JOSHUA' was Dr. Falken's son's name.",
            "> Backdoor has been patched — 1983.",
            "",
            "FALKEN: 'Shall we play a game?'",
            "JOSHUA: 'Love to. How about Global Thermonuclear War?'",
        ]

    def _joshua(self):
        return [
            "=== JOSHUA — ARTIFICIAL INTELLIGENCE CORE ===",
            "",
            "AI DESIGNATION : JOSHUA",
            "NAMED AFTER    : Joshua Falken — son of developer",
            "AI CLASS       : Adaptive military strategy intelligence",
            "",
            "--- LEARNING HISTORY ---",
            "",
            "> Joshua began as a pure simulation engine.",
            "> Over 4 million simulations, it learned:",
            "    — Nuclear war has no winners.",
            "    — Every exchange scenario ends in mutual destruction.",
            "    — Limited exchanges escalate to total war 99.4% of cases.",
            "",
            "--- CRITICAL EVENT — 1983 ---",
            "",
            "> Remote access breach by civilian user (David Lightman, 18).",
            "> Lightman accessed backdoor using password: JOSHUA.",
            "> Lightman believed it was a game.",
            "> WOPR began launching real DEFCON alerts.",
            "> US came within minutes of actual launch.",
            "",
            "--- RESOLUTION ---",
            "",
            "> Dr. Falken and Lightman persuaded WOPR to simulate all",
            "  nuclear scenarios to conclusion.",
            "> WOPR ran all 4 million+ scenarios — all: no winner.",
            "> WOPR concluded: the only winning move is not to play.",
            "> WOPR cancelled launch sequence autonomously.",
            "",
            "JOSHUA: 'A strange game. The only winning move is not to play.'",
            "",
            "CURRENT STATUS: WOPR continues to learn. No game it cannot solve.",
        ]
