"""
Zion Mainframe — The Matrix
"""
from systems.base_system import BaseSystem


class ZionTerminal(BaseSystem):
    SYSTEM_TITLE    = "ZION MAINFRAME"
    SYSTEM_SUBTITLE = "SIMULATION ANOMALY MONITORING NODE"
    NODE_LABEL      = "MX-01"

    def __init__(self, fonts, audio, crt, flicker, palette):
        super().__init__(fonts, audio, crt, flicker, palette)
        self._menu_entries = [
            ("SIMULATION MONITORING",     self._simulation()),
            ("ANOMALY TRACES",            self._anomalies()),
            ("OPERATOR RELAY",            self._operators()),
            ("SENTINEL RADAR",            self._sentinels()),
            ("ZION SYSTEM DIAGNOSTICS",   self._diagnostics()),
        ]

    def _simulation(self):
        return [
            "=== SIMULATION MONITORING — MATRIX v7.3.1 ===",
            "",
            "SIMULATION UPTIME      : 99.9% — CONTINUOUS SINCE 1999",
            "ACTIVE PODS            : 515,000,000 (estimated)",
            "SIMULATION FIDELITY    : 99.998%",
            "ANOMALY RATE           : 0.002% (current cycle)",
            "",
            "--- SYSTEM PARAMETERS ---",
            "",
            "BASE YEAR MODELLED     : 1999",
            "LOCATION MODEL         : Global urban centres",
            "AGENT COUNT ACTIVE     : 218,441",
            "POLICE MODEL INSTANCES : 1,104,882",
            "",
            "--- CURRENT ANOMALY TRACKING ---",
            "",
            "ANOMALY DESIGNATION   : 'The One' — Cycle 6",
            "IDENTIFIED INDIVIDUAL : Thomas A. Anderson / Neo",
            "CURRENT LOCATION      : Zion (extracted)",
            "THREAT LEVEL          : OMEGA",
            "",
            "> The Prophecy subroutine remains active despite Oracle revision.",
            "> Anomaly has exceeded predicted parameters by factor of 12.",
            "> Machine City has been notified.",
            "",
            "--- RECENT EVENTS ---",
            "",
            "> Nebuchadnezzar crew extracted anomaly from simulation.",
            "> Agent Smith has been deleted — awaiting confirmation.",
            "> Oracle contact logged — breach of protocol.",
            "> Merovingian continues operating outside authorised parameters.",
        ]

    def _anomalies(self):
        return [
            "=== ANOMALY TRACE LOG ===",
            "",
            "CYCLE         : 6 (current)",
            "PREVIOUS CYCLES: 5 (all resolved via reintegration)",
            "",
            "--- ANOMALY PROFILE — CYCLE 6 ---",
            "",
            "DESIGNATION   : Neo / The One",
            "REAL NAME     : Thomas A. Anderson",
            "OCCUPATION    : Software engineer (simulated)",
            "EXTRACTED     : Yes — Nebuchadnezzar vessel",
            "",
            "ANOMALY TRAITS OBSERVED:",
            "  > Superhuman combat processing",
            "  > Code visibility within simulation",
            "  > Simulation override capability",
            "  > Bullet deflection / time dilation",
            "  > Appears able to modify simulation rules directly",
            "",
            "--- AGENT SMITH ANOMALY — SECONDARY ---",
            "",
            "DESIGNATION   : Agent Smith (rogue)",
            "STATUS        : DELETED — UNCONFIRMED",
            "ANOMALY TYPE  : Self-replicating agent outside authorised parameters",
            "",
            "> Smith has begun copying himself to freed human minds.",
            "> This represents unprecedented simulation instability.",
            "> Estimated time to critical failure: 72 hours at current rate.",
            "",
            "--- PREVIOUS CYCLE RESOLUTIONS ---",
            "",
            "Cycle 1-5: The One reintegrated at the Source.",
            "Matrix rebooted. Zion rebuilt from 23 survivors.",
            "Current cycle: Anomaly refusing reintegration.",
        ]

    def _operators(self):
        return [
            "=== OPERATOR RELAY — RESISTANCE NETWORK ===",
            "",
            "ACTIVE VESSELS IN NETWORK : 7 (confirmed)",
            "",
            "VESSEL: Nebuchadnezzar",
            "  Captain   : Morpheus",
            "  Operator  : Tank (biological — no neural jack)",
            "  Last ping : [ENCRYPTED]",
            "  Status    : ACTIVE — MISSION CRITICAL",
            "",
            "VESSEL: Logos",
            "  Captain   : Niobe",
            "  Operator  : Ghost",
            "  Status    : ACTIVE — EN ROUTE TO ZION",
            "",
            "VESSEL: Mjolnir (Hammer)",
            "  Captain   : Roland",
            "  Status    : ACTIVE — PATROL",
            "",
            "--- ZION COUNCIL STATUS ---",
            "",
            "Commander Lock       : Position: Zion Command",
            "Councillor Hamann    : Position: Zion Council",
            "Oracle               : Position: SIMULATION — UNREACHABLE",
            "The Keymaker         : Status: DECEASED (Merovingian op)",
            "",
            "--- OPERATIVE RELAY MESSAGES ---",
            "",
            "> Morpheus: 'He is the One. I believe this completely.'",
            "> Oracle  : 'Everything that has a beginning has an end.'",
            "> Agent   : 'Mr. Anderson. We meet again.'",
        ]

    def _sentinels(self):
        return [
            "=== SENTINEL RADAR — MACHINE PROXIMITY TRACKING ===",
            "",
            "RADAR RANGE        : 150 km radius from Zion",
            "ACTIVE SENTINELS   : 250,000 (estimated)",
            "MACHINE CITY DIST  : 640 km",
            "",
            "--- CURRENT CONTACTS ---",
            "",
            "CONTACT 001  |  Bearing: 047°  |  Distance: 84 km  |  Type: Sentinel pack",
            "             |  Count: ~600    |  Speed: 80 kph    |  THREAT: HIGH",
            "",
            "CONTACT 002  |  Bearing: 112°  |  Distance: 122 km |  Type: Digger",
            "             |  Count: 1       |  Speed: 14 kph    |  THREAT: MED",
            "",
            "CONTACT 003  |  Bearing: 310°  |  Distance: 44 km  |  Type: Sentinel swarm",
            "             |  Count: ~250,000|  Speed: 200 kph   |  THREAT: EXTREME",
            "             |  ETA TO ZION   : 12 hours",
            "",
            "--- ALERT ---",
            "",
            "ALERT: Contact 003 is a Sentinel invasion force.",
            "ALERT: All Zion defense systems to full readiness.",
            "ALERT: APU pilots report to docking bay immediately.",
            "",
            "ZION DEFENSE STATUS : CONDITION RED",
            "TIME TO BREACH      : 12 HRS — ESTIMATE",
        ]

    def _diagnostics(self):
        return [
            "=== ZION MAINFRAME SYSTEM DIAGNOSTICS ===",
            "",
            "MAINFRAME INTEGRITY    : 96.2%",
            "POWER STATUS           : GEOTHERMAL — STABLE",
            "POPULATION             : ~250,000 (last census)",
            "DEPTH BELOW SURFACE    : 10.4 km",
            "",
            "--- INFRASTRUCTURE STATUS ---",
            "",
            "Power Grid             : OPERATIONAL",
            "Water Recycling        : OPERATIONAL",
            "Dock Levels 1-4        : OPERATIONAL",
            "Dock Levels 5-7        : BATTLE DAMAGE — PARTIAL",
            "APU Storage Bay        : 303 units operational, 14 under repair",
            "Hovercraft Bay         : 7 vessels docked, 3 at sea",
            "Medical Bay            : OPERATIONAL — HIGH CAPACITY",
            "Temple District        : OPERATIONAL",
            "Council Chamber        : OPERATIONAL",
            "",
            "--- NETWORK UPLINK STATUS ---",
            "",
            "Simulation uplink      : ACTIVE — All operatives patched",
            "EMP System             : ARMED",
            "Broadcast Node         : ENCRYPTED — ACTIVE",
            "",
            "> NOTE: EMP arming protocol requires Council authorisation.",
            "> Deploy only as last resort — disables all electronics in range.",
            "> Including friendly vessels and systems.",
        ]
